---
apiVersion: v1
kind: Namespace
metadata:
  name: litellm
  labels:
    kargo.akuity.io/project: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: litellm
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-creds
  namespace: litellm
  labels:
    kargo.akuity.io/cred-type: image
type: Opaque
stringData:
  username: sjun168
  password: "${GHCR_TOKEN}"
  repoURL: ghcr.io/sjun168/litellm
---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-repo-creds
  namespace: litellm
  labels:
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  username: sjun168
  password: "${GHCR_TOKEN}"
  repoURL: https://github.com/sjun168/platform-gitops.git
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: litellm
  namespace: litellm
spec:
  promotionPolicies:
    - stageSelector:
        name: prod
      autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: litellm-images
  namespace: litellm
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/sjun168/litellm
        imageSelectionStrategy: NewestBuild
        allowTagsRegexes:
          - "^sha-.+"
        discoveryLimit: 10
        strictSemvers: false
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: litellm
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: litellm-images
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: imageRepo
          value: ghcr.io/sjun168/litellm
        - name: gitopsRepo
          value: https://github.com/sjun168/platform-gitops.git
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitopsRepo }}
            checkout:
              - branch: main
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/clusters/prod/apps/litellm/addons/deployment.yaml
            updates:
              - key: spec.template.spec.containers.0.image
                value: ${{ vars.imageRepo }}@${{ imageFrom(vars.imageRepo).Digest }}
        - uses: git-commit
          as: commit
          config:
            path: ./repo
            message: "deploy(litellm/prod): update image to ${{ imageFrom(vars.imageRepo).Digest }}"
        - uses: git-push
          config:
            path: ./repo
        - uses: argocd-update
          config:
            apps:
              - name: litellm-prod
