apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: Business applications managed through platform GitOps.
  sourceRepos:
    - https://github.com/sjun168/platform-gitops.git
    - oci://ghcr.io/sjun168/platform-charts
  destinations:
    - namespace: app-*-dev
      server: https://kubernetes.default.svc
    - namespace: app-*-prod
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: argoproj.io
      kind: Rollout
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: external-secrets.io
      kind: ExternalSecret
    - group: external-secrets.io
      kind: SecretStore
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: policy
      kind: PodDisruptionBudget
