apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aiclaw-secrets
  namespace: app-aiclaw-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: aiclaw-secrets
  dataFrom:
    - extract:
        key: prod/app-aiclaw/app
