apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deara-env
  namespace: app-deara-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: deara-env
  dataFrom:
    - extract:
        key: dev/app-deara/app
