apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clawhost-api-service.yaml
  - externalsecret.yaml
  - networkpolicy.yaml
  - runtime-overrides-secret.yaml
  - secretstore.yaml
